spring:
  datasource:
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  profiles:
    include:
      - secret


  jwt:
    header: Authorization
    secret: JDJhJDEyJE5YVjB2MGlZMC5pL2E4MGNUTE9oMk83YldhOHlCTDRpcHducDltd0R2ZkhLNnoyZ2FleXFp
    access-token-validity-in-seconds: 86400  # 1 day
    refresh-token-validity-in-seconds: 604800  # 7 days






server:
  port: 8080